name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:  
    name: Build and Test using any available macOS
    strategy:
      fail-fast: false    
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        env:
          scheme: ${{ 'swiftui-simplex-architecture' }}
          platform: ${{ 'iOS' }}
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=$platform"
  
      - name: Test
        env:
          scheme: ${{ 'swiftui-simplex-architecture' }}
          platform: ${{ 'iOS' }}
        run: |
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform"
