name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:  
    name: Test
    strategy:
      fail-fast: false    
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test
        run: |
          make test 
